variables:
  CI_COMMIT_TAG: latest
  VITE_URL: http://172.26.92.91:8090



stages:
  - test
  - build
  - deploy

test_frontend:
  stage: test
  image: node:21.1-alpine3.17
  script:
    - cd frontend/modulecrediting
    - npm install
    #- npm run test

test_backend:
  stage: test
  image: public.ecr.aws/docker/library/maven:3.8.4-openjdk-17
  script:
    - cd backend/modulecrediting
    - mvn clean verify

build_backend:
  stage: build
  needs: ['test_backend']
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: ['']
  only:
    - main
    - develop
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}/backend/modulecrediting" --build-arg VITE_URL=$VITE_URL --dockerfile
      "${CI_PROJECT_DIR}/backend/modulecrediting/Dockerfile" --destination "${CI_REGISTRY_IMAGE}:backend-${CI_COMMIT_TAG}"


build_frontend:
  stage: build
  needs: ['test_frontend']
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: ['']
  only:
    - main
    - develop
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}/frontend/modulecrediting" --dockerfile "${CI_PROJECT_DIR}/frontend/modulecrediting/Dockerfile" --destination
      "${CI_REGISTRY_IMAGE}:frontend-${CI_COMMIT_TAG}"


deploy:
  stage: deploy
  needs: ['build_frontend', 'build_backend']
  image: nginx:1.25.3-alpine
  only:
    - main
  variables:
    DOCKER_HOST: ssh://$DEPLOY_USER@$DEPLOY_SERVER
  before_script:
    - apk update
    - apk add openssh docker docker-compose
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker compose -f docker-compose-prod.yml stop frontend backend postgres
    - docker compose rm -f frontend backend postgres
    - docker compose -f docker-compose-prod.yml up -d frontend backend postgres
