variables:
  CI_COMMIT_TAG: latest
  VITE_URL: http://172.26.92.91:8090

  # CI_REGISTRY_IMAGE: docker.io/fadefre824/swtp202312
  # CI_REGISTRY: https://index.docker.io/v1/
  # CI_REGISTRY_PASSWORD: h2#0!87tZh8027hF
  # CI_REGISTRY_USER: fadefre824
  DEPLOY_SERVER_TEST: 172.26.92.91
  DEPLOY_USER_TEST: swtp
  SSH_KNOWN_HOSTS: "172.26.92.91 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP3TtNAESWwq9RwHvzH/ZCqsDKT5XCHNmmZDrexxuslv/4AIi2Mvm0WaWH4Iv93MB3nNVAdXtXiwawZQkXRSLLs="
  SSH_PRIVATE_KEY: "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\nQyNTUxOQAAACDnCz53HMApyAwVGp8zQMlrK96CF6Iuj/hI/e/numHscgAAAKhlT6JYZU+i\nWAAAAAtzc2gtZWQyNTUxOQAAACDnCz53HMApyAwVGp8zQMlrK96CF6Iuj/hI/e/numHscg\nAAAECVZ3FmbhT0RfqrPeW5i0aOV6yz3ybPJxw8/vocg27FGecLPnccwCnIDBUanzNAyWsr\n3oIXoi6P+Ej97+e6YexyAAAAIG55NjNmYWJpQHN0dWRzZXJ2LnVuaS1sZWlwemlnLmRlAQ\nIDBAU=\n-----END OPENSSH PRIVATE KEY-----"
  # DB_HOST: db
  # DB_USERNAME: admin
  # DB_PASSWORD: 123
  # DB_PORT: 5432
  # DB_NAME: development


stages:
  - test
  - build
  - deploy

test_frontend:
  stage: test
  image: node:21.1-alpine3.17
  script:
    - cd frontend/modulecrediting
    - npm install
    - npm run test

test_backend:
  stage: test
  image: public.ecr.aws/docker/library/maven:3.8.4-openjdk-17
  script:
    - cd backend/modulecrediting
    - mvn clean verify
  

# generate_javadoc:
#   stage: build
#   image: gradle:8.4.0-jdk17-alpine
#   script:
#     - cd creditport-backend
#     - gradle javadoc
#   artifacts:
#     paths:
#       - creditport-backend/build/docs/javadoc
#   only:
#     - developer


build_backend:
  stage: build
  needs: ['test_backend']
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: ['']
  only:
    - main
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}/backend/modulecrediting" --build-arg VITE_URL=$VITE_URL --dockerfile
      "${CI_PROJECT_DIR}/backend/modulecrediting/Dockerfile" --destination "${CI_REGISTRY_IMAGE}:backend-${CI_COMMIT_TAG}"


build_frontend:
  stage: build
  needs: ['test_frontend']
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: ['']
  only:
    - main
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}/frontend/modulecrediting" --dockerfile "${CI_PROJECT_DIR}/frontend/modulecrediting/Dockerfile" --destination
      "${CI_REGISTRY_IMAGE}:frontend-${CI_COMMIT_TAG}"


deploy:
  stage: deploy
  #needs: ['build_frontend', 'build_backend']
  image: nginx:1.25.3-alpine
  only:
    - main
  variables:
    DOCKER_HOST: ssh://$DEPLOY_USER_TEST@$DEPLOY_SERVER_TEST
  before_script:
    - apk update
    - apk add openssh docker docker-compose
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker compose -f docker-compose-prod.yml stop frontend backend postgres
    - docker compose rm -f frontend backend postgres
    - docker compose -f docker-compose-prod.yml up -d frontend backend postgres