version: "3.7"

services:

  frontend:
    container_name: frontend
    image: docker.io/japark999/swtp_frontend:latest
    ports:
      - 8080:8080

  backend:
    container_name: backend
    image: docker.io/japark999/swtp_backend:latest
    ports: 
      - 8090:8090