version: "3.7"

services:
  frontend:
    container_name: frontend
    image: ${CI_REGISTRY_IMAGE}/swtp_frontend:latest
    ports:
      - 8080:8080
  backend:
    container_name: backend
    image: ${CI_REGISTRY_IMAGE}/swtp_backend:latest
    ports: 
      - 8081:8080
