version: '3.7'

services:

  postgres:
    container_name: postgres_container
    ports:
      - 5432:5432
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes: 
      - backend_db:/var/lib/postgresql/data
    restart: always
    networks:
      - swtp_network

  backend:
    container_name: backend
    image: fadefre824/swtp202312:backend-latest
    restart: always
    depends_on: 
      - postgres
    ports: 
      - 8090:8090
    networks: 
      - swtp_network
    environment:
      - DB_SERVER=postgres
      - DB_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      
      
  frontend:
    container_name: frontend
    image: fadefre824/swtp202312:frontend-latest
    restart: always
    depends_on:
      - backend
    ports:
      - 8080:80
    networks: 
      - swtp_network
    environment:
      - VITE_URL_TEST=http://172.26.92.91:8090

volumes:
  backend-db:
    name: backend_db

networks:
  swtp_network:
    name: swtp_network
