version: "3.7"

services:

  frontend:
    container_name: frontend
    image: docker.io/japark999/swtp_frontend
    depends_on:
      - backend
    ports:
      - 9001:80
    networks: 
      - swtp_network

  backend:
    container_name: backend
    image: docker.io/japark999/swtp_backend
    depends_on: 
      - postgres
    ports: 
      - 8090:8090
    networks: 
      - swtp_network
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

  postgres:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    networks:
      - swtp_network
    ports:
      - "5432:5432"

networks:
  swtp_network:
